### ISSUE TITLE
Restructure and cleanup

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-welcome#1]
Ok - first things first.  It doesn't matter if we take Antergos as the base or Ubuntu MATE. There is an lot of the Ubuntu MATE Welcome we need that is not covered by Antergos. Likewise there is a lot of Ubuntu MATE Welcome that we don't need.  

- If we take the Antergos as base then we'll need to copy the relevant MATE screens that we are going to reuse ... together with the linked images, css, javascript etc.  - I suspect this will be more work with this approach - effectively recoding stuff that has been already written.

- If we take the MATE Welcome as base (what we have at the moment), we need to cleanup and remove the cruft. Lets assume the MATE Welcome as base - i.e. what we have at the moment.

The current file and folder structure of the welcome source is good to proceed. In the Data folder:

1. Delete `shop.html`, `rpi.html`, `gettingstarted.html`, `helloguest.html`, `hellolive.html`, `involved.html`, `readme.html`, <del>`software.html`, `software-only.html`</del> and `splash.html`
2. Delete `fonts` folder.
3. Move aside contents of the `img` folder. Then launch firefox and open welcome.html, move back all the missing images until the screen works again i.e. click the refresh button to force a reload.

Specific "mate" named files should be replaced by "distro" - this is so that when we move from "budgie-remix" to "Ubuntu Budgie" we won't have to rework the filenames. For e.g. `welcome/ubuntu-mate-gray.svg` would need to be named `welcome/distro-gray.svg`.

The other pages are covered by individual issues.

**Comment by apolitech** [comment]
1 Question! If we deleate  helloguest.html, hellolive.html we will not deleate the installer that appears when you boot up via a usb/dvd?
