### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-welcome#12]
place-holder issue.

Need to validate all of the listed shortcuts - most look like "GNOME2" rather than budgie/GNOME-Shell.

It mentions "Compiz" - obviously not applicable for budgie-desktop

budgie-desktop specific shortcuts e.g. raven alt+N
applications alt +f2
ctrl+alt+del - exit the desktop

**Comment by niyasc** [comment]
This issue is addressed by commit  https://github.com/budgie-remix/budgie-welcome/commit/5eb5909c47515d6c94664dd0275a341a2bbb7eaa

Please check it and close this issue if problem is resolved.
