### ISSUE TITLE
Improvements to Recommendations page

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-welcome#14]
- From a presentation point of view, snaps should be at the top of the page and not at the bottom
- We should add a recommendation to install the `budgie-screenshot-applet` as well
- Assuming we get official status, a recommendation would be to add our PPA to get the latest stuff! But, let's worry about that later :smile:

**Comment by niyasc** [comment]
- Changed order of recommendations. Placed `Snap` at the top. https://github.com/budgie-remix/budgie-welcome/commit/1307c1fc0173ecc2c6bcd98751858656315a66c5
- Added recommendation to install `budgie-screenshot-applet`. https://github.com/budgie-remix/budgie-welcome/commit/b532fdb9624e438b233c5822944c6916a2ef8ffe
  
 **TODO** Add newly installed applet to `budgie-panel`

**Comment by fossfreedom** [comment]
There is no api to add a applet automatically.

We should just say "after installation, use Raven to add the applet to your panel"
