### ISSUE TITLE
Include the ability to reset Budgie shell/panels

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-welcome#19]
Like `unity --reset` and similar options provided by desktop shells, Budgie should have the ability to do a full reset.

Upstream Budgie doesn't have such an option currently. However, we can add a big button somewhere in the _Budgie Welcome_ app together with a command line option.

To do a reset, kill the budgie-panel process, then reset gsettings:

    dconf reset -f /com/solus-project/budgie-panel/

and finally relaunch budgie-panel:

    nohup budgie-panel --replace &

For the command line variant, lets add a `--reset` argument to _Budgie Welcome_ to do the above.

**Comment by niyasc** [comment]
I'm thinking to put this feature and the option to switch between **Arc** and **Material Design** together in a single page called `Factory Settings`. 

Then provide an option in index page as follows to open `Factory Settings`.
![mockup](https://cloud.githubusercontent.com/assets/2451833/17150390/e1dc71d0-538c-11e6-8ef0-59fd1a3a503d.png)

@budgie-remix/welcome-app 

What is your opinion on this?

**Comment by fossfreedom** [comment]
"Settings" or "Default Settings" is probably better since "Factory Settings" kind of has a very specific meaning and we want this option to control lots of different things in the future.

Yeah - like the idea of putting it side by side with software center +1
