### ISSUE TITLE
Modify the look and style

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-welcome#2]
ok, 

  with regards to the actual welcome screen

![ubuntu xenial running - oracle vm virtualbox 1_028](https://cloud.githubusercontent.com/assets/996240/15336818/4e985856-1c70-11e6-80d6-3dc832931448.png)

@Udara-U3 any chance you can do a .png for the header "budgie-remix"?

Installation Help #1 is removed

I think the button colours should be the same as chat-room & community.

Maybe only use "dark arc themed" buttons for "Getting Started" and "Get Involved" - two areas we want people to definitely click.

Is there anyway we can get the icons to line up - it looks messy currently.  Maybe indent icons from the left and right align text?  @Udara-U3 what do you think?

Is there a way to get either the Install/software buttons to appear in the center below the logo?

@HEXcube are there moka icons that we can use to replace the current icons in the picture?

Obviously need to display "install" in live CD mode and "Software" in installed mode - will raise a separate issue about changing the python script running the app.

**Comment by Udara-U3** [comment]
@fossfreedom Yeah of course I'll make a .PNG or SVG for header.
And about the buttons I'm totally agree with you, It should be a one theme.

Yes It'll be better, Icons looks messy. Yeah It would be nice. Icon from the left and right align Text. But maybe Text also from the left align next to Icons.

And about the Install/software buttons also It's a nice idea :+1:

**Comment by HEXcube** [comment]
> are there moka icons that we can use to replace the current icons in the picture?

I'm not sure, but I think Faba (Moka's base icon theme) has symbolic icons we can use here. :confused: But for the featured app and software boutique icons, we can use Moka icons like we did for Ubiquity Slideshow. :relaxed:

**Comment by Udara-U3** [comment]
Ok Here we go.., **I just created UI Mockup for Welcome App**
What are you guys Ideas and opinions  ?

![welcome](https://cloud.githubusercontent.com/assets/12265797/15351993/2761753c-1cf3-11e6-8a66-9261d96ed8dd.png)

**Comment by fossfreedom** [comment]
that looks amazing.  Just amazing.  Well done :)

"Installation Help" (since this is very "Ubuntu MATE" and too big to deal with this cycle) we are going to remove for this cycle which will leave the right side unbalanced.  So we probably should combine "Chat Room" with "Community" to balance the icons (just have one button called "Chat & Community")

**Comment by Udara-U3** [comment]
Thanks :smile:  I'm just always trying to do something clean and nice. 
But why should we merge that buttons. We can just keep them and we can change that Chat room to **Live Help** or something like that then we can keep both of them. Otherwise It'll be unbalanced :confused:

**Comment by fossfreedom** [comment]
left hand side would be 3 icons (introduction, features, getting started) and the right side would be 4 icons (chat/live help [I like that "live help"]), Community, get involved, "Donate"

**Comment by Udara-U3** [comment]
But if we do like that It'll be unbalanced and not nice, Can't we do anything for that ? :worried:

**Comment by fossfreedom** [comment]
we would need to invent a new area for the "Installation Help" ... or keep "Installation Help" and just have a web-page with some instructions.  Ok - lets do that - Installation Help and we'll come up with some instructions on how to install.

**Comment by Udara-U3** [comment]
Yeah that wold be great :+1:

**Comment by apolitech** [comment]
Maybe trying to have the fonts from features etc bold?

**Comment by Udara-U3** [comment]
@apolitech Yeah It's gonna be okay in real App, Because if you can zoom the Mockup and look You'll see the actual size of that font. After exporting it to raster images we can't see actual view just looking at it.  :smile:

**Comment by niyasc** [comment]
Hi,

I would like know status of this project. I don't see any progress in repository. Is there any work going on? If not I prefer to particpate in UI changing activity.

Regards.

**Comment by fossfreedom** [comment]
Hi @niyasc 

  Development has only just started - @HEXcube is making some initial changes to the main screen (index.html) in his branch (Hex).

Issue #1 describes how we intend to restructure the project - which screens (web-pages) we are going to concentrate on first.  Mainly picture and word changes.

Once done we'll get into the fun parts of making the welcome app truly dynamic.

Feel free to pop in to our general chatroom - say hi - we may not be immediately around but just leave a window open and someone will respond as soon as possible.

https://gitter.im/budgie-remix/community

**Comment by HEXcube** [comment]
Hi @niyasc ! Thanks for the pull request improving README. :relaxed: @fossfreedom merged it a few hours ago.

And about the changes, I just merged my branch with `master` a while ago. And I'll be working on the main branch now. So, you'll be able to easily see the changes being made. :smile:

And yes, we'd love to have more contributors working on our projects. :relaxed: So, If you're interested feel free to contact us.

**Comment by niyasc** [comment]
Hi, I was just working on first screen of welcome app and now it is looking like this.
![welcome screen](https://cloud.githubusercontent.com/assets/2451833/15921134/f73d9790-2e3c-11e6-9b15-bdf88cdf8c61.png)

This change is not committed yet. Do you have any suggestions regarding this?

**Comment by Udara-U3** [comment]
@niyasc Seems like we have to do lot of improvements. Can you read all comments of this post, Then you'll understand why I have created UI Mockup for this app. btw Good work :smile

**Comment by fossfreedom** [comment]
@niyasc excellent progress.  Four visual issues.

The logo is unbalanced in size - it needs to be no larger in height that the size of the buttons vertically.

The buttons should be arc-themed if possible

The button icons should Moka based - the mockup has them placed on the left hand side of the buttons.

The icons and two bottom buttons need to be arc-blue - the palette colours are in our assets database

 - https://github.com/budgie-remix/assets/tree/master/Color%20Palette

**Comment by niyasc** [comment]
@fossfreedom @Udara-U3 Thaks for your feedback. 

- Regarding logo size, some more margin needs to be applied on buttons to match with Mockup. After that, I thinkg logo size will be matching.
- I did n't know that, there is a color palette available for Arc theme. For time being I was using default bootstrap color scheme, and `google blue`

**Comment by HEXcube** [comment]
> I didn't know that there is a color palette available for Arc theme. For time being I was using default bootstrap color scheme, and google blue

Yeah, **Budgie** desktop and **Solus** follow the style and color scheme of [Arc GTK theme](https://github.com/horst3180/arc-theme). So, we picked some main colors used by Arc and made a [simple color palette](https://github.com/budgie-remix/assets/tree/master/Color%20Palette/) for the convenience of budgie-remix devs and designers. If u want more colors, this is the [full list of colors defined by Arc](https://github.com/horst3180/arc-theme/blob/master/common/gtk-3.0/3.18/sass/_colors.scss).

**Comment by HEXcube** [comment]
> Hi, I was just working on first screen of welcome app and now it is looking like this.
> 
> ![welcome screen](https://cloud.githubusercontent.com/assets/2451833/15921134/f73d9790-2e3c-11e6-9b15-bdf88cdf8c61.png)

@niyasc U don't have the Ubuntu fonts installed on ur system, do u? :wink:

**Comment by niyasc** [comment]
@HEXcube That screenshot was taken on office PC running windows. :grimacing: .

**Comment by HEXcube** [comment]
@niyasc  K..I see. Try installing [Ubuntu font](http://font.ubuntu.com/) on Windows then? :relaxed:

**Comment by niyasc** [comment]
@HEXcube . As I mentioned, it is office PC. I don't have even permission to install font. :cry:  But it is not an issue in my personal laptop. I have Ubuntu font installed. But I have no idea, whether the App is showing Ubuntu font or not.

You can see update screenshot [here](https://raw.githubusercontent.com/budgie-remix/budgie-remix-welcome/master/screenshot.png).

**Comment by Udara-U3** [comment]
@niyasc **That seems so cool** :smile: **Great job..** :+1:
I have used in that UI Mockup It's [Google Material Icons](https://design.google.com/icons/) you can use them. 

So budgie-remix logo I have attached in above [comment](https://cloud.githubusercontent.com/assets/12265797/15348057/30785188-1cd8-11e6-97e3-6c5bd9f0926d.png). So you can use it.

So for that **blue color** this is the color code `#4c8ac9` it's for icons & Main Buttons.
Grey color is **Arc Grey** `#404552` it's for Buttons, Header & Footer.

If you need any help with other colors, just contact me :relaxed:

**Comment by niyasc** [comment]
@Udara-U3 . Actually I was looking for these color codes. Thanks for help.

What about the effect when _hover_  on buttons? What effect we should use?

**Comment by fossfreedom** [comment]
these type of effects?  kind of like the understated ones like shadow-radial

 - http://ianlunn.github.io/Hover/

**Comment by niyasc** [comment]
@fossfreedom . Wow, there are too many effects. I'm seeing this for the first time. But there are too many options. I'm very poor in selecting things :cry:  

Though shadow effect is looking good.

@Udara-U3 What do you think? Which one will be good for our purpose?

**Comment by niyasc** [comment]
![welcome screen](https://cloud.githubusercontent.com/assets/2451833/16001374/3f006938-316f-11e6-8d85-65f200d218e1.png)

Btw, @Udara-U3 I have updated welcome screen based on your suggestion. However, I was not able to find icon used for contribute button.

**NB** : Don't complaint about font :grin:

**Comment by Udara-U3** [comment]
@niyasc So for the hover effect, First shadow effect is good, you can also use some bit light color on the button when hover. It would be nice :smile: 
And I think you should increase button heights a bit. also Blue buttons should be main buttons so they should be larger than other buttons :smile: 
Finally I think we don't need **16.04** because we'll use this with our every release. So it would be better without it.

**Comment by niyasc** [comment]
Material Icons are properly displayed in browser. But it is not working correctly in app. Any idea about this? @Udara-U3 

![material-icon-breaking](https://cloud.githubusercontent.com/assets/2451833/16013597/b4697fde-31ab-11e6-8080-4e028552b29b.png)

**Comment by fossfreedom** [comment]
Might be because the app is using the very old webkit to display the pages. Will need to try webkit 2 or latet

**Comment by niyasc** [comment]
@fossfreedom  I don't think so. I just tried with WebKit2. Still it is not working.

Also, It is not working on `epiphany 3.18` - A webkit based browser by GNOME. Can anyone confirm this issue?

If we are not able to find a solution for this problem, we'll have to revert to `font-awesome`.

**Comment by Udara-U3** [comment]
@niyasc What did you use for this ? I mean **SVG or PNG** if it's SVG, Try to use PNG or use Material Icons font yo can grab it [here](http://google.github.io/material-design-icons/#icon-font-for-the-web)

**Comment by HEXcube** [comment]
@Udara-U3 Well, he's already using that one. :confused: See [data/font/](https://github.com/budgie-remix/budgie-remix-welcome/tree/master/data/font/) and [data/css/material-icons.css](https://github.com/budgie-remix/budgie-remix-welcome/blob/master/data/css/material-icons.css) from the repo.

**Comment by niyasc** [comment]
@Udara-U3 

I was using icon font as mentioned in that document which is as follows.
```
      <i class="material-icons">info</i>
      <i class="material-icons">help</li>
```

Ok. I think, I got your point. I will use SVG or PNG images instead of using icon font.

**Comment by Udara-U3** [comment]
Ohh I see, Yeah use SVG or try it with Self hosted Material Icons font, because if not it requires Internet to import it, maybe it's the problem. SVG is the better choice rather than PNG, Because SVG is vector Based so No quality losses with Bigger displays :smile:

**Comment by HEXcube** [comment]
The icon outside button style looks rather wierd! :worried:  It didn't look bad in @Udara-U3's mockup but I think it's better to have them as mocochrome icons inside the button itself, like the way it's shown in _'Software'_ and _'Install Now'_ buttons. Well, what do you think @Udara-U3 and @niyasc ? :confused:

**Comment by HEXcube** [comment]
> As I mentioned, it is office PC. I don't have even permission to install font.  But it is not an issue in my personal laptop. I have Ubuntu font installed. But I have no idea, whether the App is showing Ubuntu font or not.

Made the wordmark a path so it could be used even without installing Ubuntu font! :relaxed: See [this commit](https://github.com/budgie-remix/assets/commit/83e6e61576cd0542b2b41a990adee8ef83987617).

So @niyasc, u can use the [updated wordmark](https://raw.githubusercontent.com/budgie-remix/assets/master/Logos/budgie-remix-wordmark-dark.svg) now :smiley:

**Comment by niyasc** [comment]
@HEXcube . Ok, I understand that now `.svg` banner can be used instead of `.png` banner. But how does it deal with ubuntu font? Existing `.png` banner is already using ubuntu font? Is n't it?

**Comment by Udara-U3** [comment]
@niyasc No no, `PNG` is a raster image, so it doesn't require anything to display. but `SVG` is vector, SVG means "Scalable Vector Graphics"  so it's keeping original quality with any of monitor sizes, but `PNG` is not like that because it's Raster.

So in vector graphics using original content and it's editable same like our wordmark, so what @HEXcube meant he as converted our wordmark font to path, so that means it not requires any font to render, it's rendering itself. :smile:

**Comment by HEXcube** [comment]
@Udara-U3 Thanx for explaining :relaxed:

@niyas What Udara said

**Comment by niyasc** [comment]
@HEXcube @Udara-U3 . Thanks for the information. I will update it soon.

Meanwhile, I was able to solve problem related to material icons. Actually, there are two ways to use material icons. One by symbol name and other by typical `&#XXXX;` approach.

     
     <i class="material-icons">cloud</i>

     
     <i class="material-icons">&#xE2BD;</i>

I was using first approach because in comment it is mentioned that second one is for IE9 or previous browsers. But I realized that, we need to use second option with `WebKit` also, even if it is version 2.

**Comment by fossfreedom** [comment]
Can I ask - I presume the icons are locally stored ... i.e. not downloaded via the web?  The app needs to work offline.

**Comment by niyasc** [comment]
Google material icon is a kind of font similar to `font awesome`. So I have removed all `font-awesome` related files and `material-icons` fonts are added in [fonts](https://github.com/budgie-remix/budgie-remix-welcome/tree/master/data/font) directory.

Surely, It will work offline.

**Comment by niyasc** [comment]
Latest screenshot is here. Introduction button is showing hover effect. Observe a minor color change and small shadow.
![screenshot](https://cloud.githubusercontent.com/assets/2451833/16090224/35514504-334c-11e6-81ff-69cc02f33c61.png)

> The icon outside button style looks rather wierd! :worried: It didn't look bad in @Udara-U3's mockup but I think it's better to have them as mocochrome icons inside the button itself, like the way it's shown in 'Software' and 'Install Now' buttons. Well, what do you think @Udara-U3 and @niyasc ? :confused:

Well, what do you think @Udara-U3?

**Comment by Udara-U3** [comment]
@niyasc I don't have that problem, we'll ask from David @fossfreedom about this & his opinion,
Now seems much better :smile: you have done a Great job @niyasc :+1: 

So I have noticed that first button color is still black or it's hover effect ? I'm curious about it.
**I can give you small tips to make this better** :smile:  

- Make blue icons same height with buttons
- If you can increase height of buttons a bit, I think it would be better
- Finally in the Blue main buttons if you can make bit Padding around, I mean increase button size 
  without increasing text and make it center of the button.

**Comment by Udara-U3** [comment]
@budgie-remix/welcome-app  
**I just made a UI mockup with some of Improvements** :smile: 
Check this out and let me know about your opinions.
 ![welcome_new](https://cloud.githubusercontent.com/assets/12265797/16092284/d3e96faa-333f-11e6-9561-032c53bea442.jpg)

**Comment by fossfreedom** [comment]
@niyasc nice job.  Agree with @Udara-U3 the material icons on the outside look good.  :+1:  :+1: :+1:

**Comment by Udara-U3** [comment]
@fossfreedom What do you think about my new UI Mockup ? 

**I have made some improvements with it,**
- Added **Social icons** to left side footer
- Increased **icon sizes** to Button heights
- Moved footer **text and Radio button to right side**

**Comment by fossfreedom** [comment]
nice job.  So we've actually got reddit, G+ and github.  Have we got a facebook and twitter as well?

Yeah - the icon sizes to be button heights is a very good idea. like it :)

**Comment by niyasc** [comment]
@Udara-U3 
> So I have noticed that first button color is still black or it's hover effect ? I'm curious about it.

Yes. It is hover effect.

New UI mockup look good for me. But I have some implementation issue for checkbox at bottom right. Since it is a single symbol in `material-font` I think, it is difficult to apply two colors (blue and white).

**Comment by niyasc** [comment]
Current status.
![welcome screen](https://cloud.githubusercontent.com/assets/2451833/16108864/59d4eba2-33c3-11e6-8728-9ec77667d07d.png)

@Udara-U3 
Where did you get those social media icons? : I don't see them in material icon collection.

**Comment by Udara-U3** [comment]
@fossfreedom Here I have updated Social icons :smile: 
 ![updated](https://cloud.githubusercontent.com/assets/12265797/16111251/5515849a-33ba-11e6-98b5-ef16b5e74572.jpg)

@niyasc No there no any download links for that,I have created them, I'll share them with you in SVG format :wink:

**Comment by bryku** [comment]
Honestly i sort of liked the different colors, It is nice an sleek... but, generic. Looks like every wordpress website out there.

**Comment by smpro1101** [comment]
i'll be glad to help for Persian translation if needed.

**Comment by fossfreedom** [comment]
@smpro1101 many thanks for the offer.  All translation work is carried out on transifex - so please can you request the language and sign in as translator there.  Thanks

https://www.transifex.com/ubuntu-budgie/budgie-welcome/

**Comment by smpro1101** [comment]
@fossfreedom Sure, I have done it just know.

**Comment by fossfreedom** [comment]
done - cheers @smpro1101 :)
