### ISSUE TITLE
16.04.1 Testing - Lock screen setting has no effect

### ISSUE THREAD

**Issue by makitso** [budgie-remix/budgie-welcome#20]
Running in Virtual Box:

Settings/Background,  Looks like changing the Lock Screen has no effect when the screen is locked.

**Comment by Udara-U3** [comment]
@makitso Known issue you can track progress here https://github.com/budgie-remix/budgie-artwork/issues/5  will fix this issue in future, for now you can install `lightdm-gtk-greeter-settings` then change Lock screen using it :smile:

**Comment by niyasc** [comment]
Closing this issue because:

- It is not related to `budgie-welcome`
- Known issue and is already reported at https://github.com/budgie-remix/budgie-artwork/issues/5
- Upstream is working on alternative project to address this issue. https://github.com/solus-project/lightdm-budgie-greeter
