### ISSUE TITLE
Material theme suggestions

### ISSUE THREAD

**Issue by niyasc** [budgie-remix/budgie-welcome#25]
In order to implement a user-based option to switch between *Material Style* and *Arc Style*, we need to find out a good theme that follows *Material Design* guide lines.

A few suggestions are listed here. Please update this list if you know some other themes and share your opinion on *best* theme.

Theme type | Available themes
-------------|-----------------
GTK Theme | [Paper](https://snwh.org/paper/theme), [Adapta](https://github.com/tista500/Adapta), [Flat-Plat](https://github.com/nana-4/Flat-Plat)
Icon theme | [Paper](https://snwh.org/paper/icons), [Frosting](https://github.com/crutchcorn/frosting-icon-theme)
Cursors      | [Paper](https://snwh.org/paper/cursors)
Background | Use a wallpaper in standard package or something different?

## Paper Theme(GTK, Icon, Cursor)
![01](https://cloud.githubusercontent.com/assets/2451833/17297347/0295fb36-5823-11e6-9dd4-2d8d65c3cb7b.png)
![02](https://cloud.githubusercontent.com/assets/2451833/17297348/02f9a85c-5823-11e6-8ec9-94b5e02cc274.png)
![03](https://cloud.githubusercontent.com/assets/2451833/17297349/030329ae-5823-11e6-8b75-ff793e3ddafa.png)
![4](https://cloud.githubusercontent.com/assets/2451833/17297400/30fab50c-5823-11e6-9eac-20e75a124cea.png)

**Comment by Udara-U3** [comment]
GTK Theme : Adapta
Icon theme : Paper
Courser       : Paper

**Comment by fossfreedom** [comment]
Screenshots! Kind of want to see how budgie-desktop would look.

**Comment by niyasc** [comment]
Currently screenshots can be seen if you follow given links. I will updated `budgie-remix` screenshots by evening.

**Comment by fossfreedom** [comment]
@niyasc is that with your transparency fix as well?    Absolutely gorgeous - would support this :)

**Comment by Udara-U3** [comment]
@fossfreedom Yeah I made that transparency and removed shadow :smile: That's cool :+1:

**Comment by HEXcube** [comment]
I could find only **Paper** icon theme that's both well maintained and close to Material Design guidelines. Most other icon themes are just _Flat Design_ themes wrongly branded as Material. :disappointed:

- There's **Frosting** (successor to Solus' old icon theme **Evopop**), but not actively maintained now
- **Papyrus** is a derivative of **Paper**, but I don't see any improvement in quality
- **Super Flat Remix** doesn't have a consistent style due to mixing Material and Flat icons from different icon themes

**Comment by niyasc** [comment]
There is one *Material* inspired OS named [Papyros](http://papyros.io/). It seems they are making use of all *paper* stuffs.

**Comment by HEXcube** [comment]
> There is one Material inspired OS named Papyros.

Seems u confused [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-gtk) with [Papyros Shell](http://papyros.io/).:confused:  The names are too similar :grin:

**Comment by fossfreedom** [comment]
ok - can someone fix the last bit please? getting "bad substitution on the for loop at the end of the script

```
#!/bin/sh

the_ppa='snwh/pulp'
if ! grep -q "$the_ppa" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
    # commands to add the ppa ...

    sudo add-apt-repository -y ppa:$the_ppa 
    sudo apt-get update
    sudo apt install -y paper-gtk-theme paper-cursor-theme paper-icon-theme
fi

gsettings set org.gnome.desktop.interface gtk-theme 'Paper'
gsettings set org.gnome.desktop.interface icon-theme 'Paper'
gsettings set org.gnome.desktop.interface cursor-theme 'Paper'
gsettings set org.gnome.desktop.background color-shading-type 'solid'
gsettings set org.gnome.desktop.background picture-options 'wallpaper'
gsettings set org.gnome.desktop.background picture-uri 'file:////usr/share/gnome-control-center/pixmaps/noise-texture-light.png'
gsettings set org.gnome.desktop.background primary-color '#008094'
gsettings set org.gnome.desktop.background secondary-color '#008094'

# you could in theory have multiple docks - so need to get dock names and substitute as appropriate
gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/dock1/ theme 'Gtk+'
#gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/dock2/ theme 'Gtk+'

# get docks into a string and remove the [] around the string
larray=`gsettings get net.launchpad.plank enabled-docks | sed -r 's/(\[|\])//g'`
# convert into an array
array=$(echo $larray | tr "," "\n")
for element in "${array[@]}"
do
    gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/$element/ theme 'Gtk+'
done
```

**Comment by niyasc** [comment]
@fossfreedom 
I'm at work right now. So can't test the script.

But one thing regarding theme installation
- If we use `sudo` we need to provide password in terminal, and it is not possible when we are using **Welcome App**
- If we invoke script with elevated privileges, theme will be applied on root account and not on user account.

So my suggestion is to keep two buttons, one for installation and other for applying theme.
- If theme is not installed, `install` button(only) should be available.
- If theme is installed then only `apply` button should be available.

**Comment by Udara-U3** [comment]
@fossfreedom Are we using **Paper GTK theme** instead of **Adapta** ? :confused:

**Comment by fossfreedom** [comment]
@niyasc understand - feel free to rework the script - it was just to give everyone an idea of what we need to rework everything.

@Udara-U3 honestly don't mind - as I said - just an example script to show how to retheme/change icons.  

I'll try to do a "reset" script later.

**Comment by fossfreedom** [comment]
ok - revised script - rejigged the plank retheming bit and copes with multiple docks

````
#!/bin/bash

the_ppa='snwh/pulp'
if ! grep -q "$the_ppa" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
    # commands to add the ppa ...

    sudo add-apt-repository -y ppa:$the_ppa 
    sudo apt-get update
    sudo apt install -y paper-gtk-theme paper-cursor-theme paper-icon-theme
fi

gsettings set org.gnome.desktop.interface gtk-theme 'Paper'
gsettings set org.gnome.desktop.interface icon-theme 'Paper'
gsettings set org.gnome.desktop.interface cursor-theme 'Paper'
gsettings set org.gnome.desktop.background color-shading-type 'solid'
gsettings set org.gnome.desktop.background picture-options 'wallpaper'
gsettings set org.gnome.desktop.background picture-uri 'file:////usr/share/gnome-control-center/pixmaps/noise-texture-light.png'
gsettings set org.gnome.desktop.background primary-color '#008094'
gsettings set org.gnome.desktop.background secondary-color '#008094'

# you could in theory have multiple docks - so need to get dock names and substitute as appropriate
#gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/dock1/ theme 'Gtk+'
#gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/dock2/ theme 'Gtk+'

# get docks into a string and remove the [] around the string
larray=`gsettings get net.launchpad.plank enabled-docks | sed -r 's/(\[|\])//g'`
# convert into an array
array=$(echo $larray | tr "," "\n")
for element in "${array[@]}"
do
    element=`echo "$element" | tr -d "'"`
    echo $element
    gsettings set net.launchpad.plank.dock.settings:/net/launchpad/plank/docks/$element/ theme 'Gtk+'
done
```
