### ISSUE TITLE
Global network status - Opinion required

### ISSUE THREAD

**Issue by niyasc** [budgie-remix/budgie-welcome#26]
Currently **Welcome App** shows "Not Connected" message in some pages if network is not available. You can check this using command line argument `--force-no-net`.

![not connected](https://cloud.githubusercontent.com/assets/2451833/17373532/3d6729d4-59c6-11e6-813a-449dc99f0490.png)

What is is your opinion about replacing these messages with a global network icon as shown in figure?
![network](https://cloud.githubusercontent.com/assets/2451833/17373557/5e7315b6-59c6-11e6-99ce-65eb0c4c78fd.png)

### Additional change
- Disable all install buttons if network is not available

### Advantage
- Reconnect action can be initiated from any page.

**Comment by HEXcube** [comment]
Aren't those indicators kinda redundant with the network indicator on system panel? :confused: 

But, disabling buttons for all internet needing stuff when offline seems like a good idea :+1:

**Comment by niyasc** [comment]
Yes. It appears as redundant. Closing this issue.
