### ISSUE TITLE
Install apps error

### ISSUE THREAD

**Issue by apolitech** [budgie-remix/budgie-welcome#29]
You will get a error wile trying to install apps from recommendation tab in ubuntu 16.04.1

**Comment by niyasc** [comment]
For which app, you are getting error? Can you please provide more details?

**Comment by apolitech** [comment]
All the apps (steam have the problem that we know). Flatpak applet etc. 16.04.1 fresh install and up to date. Right now i dont have the os install because of some heating problem. I will install in vm  if you whant some aditional info

**Comment by niyasc** [comment]
You don't have to do an OS install. Please run `budgie-welcome` with command line arguments `--force-session=live` and share the log that you see on terminal when trying to install application.

**Comment by apolitech** [comment]
Yea you are right but first i need to upgrade it

**Comment by niyasc** [comment]
@fossfreedom Seems that, this issue is caused by missing `privileged-actions` script file. I have added it to `.install` file. Please confirm this, when you do packaging next time.

**Comment by fossfreedom** [comment]
v0.3.9 released
