### ISSUE TITLE
Recommendations page header disappears on scrolling

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-welcome#30]
hmm - the scrolling issue with the recommendations header is back again - you can scroll down the page and the recommendations header disappears.

**Comment by apolitech** [comment]
In 16.04.1 its the same version . did not get any update soo the issue never disappeared

**Comment by fossfreedom** [comment]
fixed in this commit https://github.com/budgie-remix/budgie-welcome/commit/bc2e60a7f94e1e26357620deae217ca9c488c8a2
