### ISSUE TITLE
javascript issues stopping inclusion into upstream repos

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-welcome#32]
Canonical devs have commented about these issues:

E: budgie-welcome source: source-is-missing data/js/bootstrap.min.js
E: budgie-welcome source: source-is-missing data/js/tether.js line length is 566 characters (>512)

Debian does not like the unreadable javascript files  - we should find the non-compressed versions of these files and the debian package should use "uglifyjs" to-do the compression.

@niyasc - any ideas where we can get the non-compressed versions of those files?

https://github.com/twbs/bootstrap ???

I'll do the packaging changes to recompress the sources.

**Comment by fossfreedom** [comment]
@niyasc ok - I've added bootstrap.js and a beautified tether.js

Question - we should delete bootstrap.min.js ... and somehow generate bootstrap.min.js from bootstrap.js - via a makefile??  Any thoughts how to do this.

**Comment by HEXcube** [comment]
I know it's a bit late, but here's the source for Bootstrap v4 (the version we're using in Welcome app):

[Website](https://v4-alpha.getbootstrap.com)
[GitHub repo](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css)
