### ISSUE TITLE
uplift to bootstrap alpha 4

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-welcome#35]
bootstrap.js is now at alpha 4

however bootstrap.min.css is alpha 2

investigate moving bootstrap.min.css to alpha 4 - or later

**Comment by niyasc** [comment]
- Updated `bootstrap.min.css` to alpha 4.
- Fixed broken color schemes for buttons and links.
- Replaced `col-md-push-*` with `push-md-*` which is bootstrap 4
  convention.
- This is only tested on web browser and need to be tested on app.
