### ISSUE TITLE
Switch to Material Design fails

### ISSUE THREAD

**Issue by Udara-U3** [budgie-remix/budgie-welcome#38]
![virtualbox_beta 01_18_09_2016_15_55_53](https://cloud.githubusercontent.com/assets/12265797/18632022/491bcde0-7e86-11e6-9210-953b26f8011c.png)

**Comment by fossfreedom** [comment]
needs both adapta and paper PPA's to have 16.10 packages

**Comment by niyasc** [comment]
We need to check availability of PPA just after user click on install button and show immediate error message if it is not available.

**Comment by fossfreedom** [comment]
should be fixed now - Sam has updated his PPA.
