### ISSUE TITLE
recommendation - flatpak for yakkety

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-welcome#39]
flatpak is available in the repos without the need for a PPA.

**Comment by niyasc** [comment]
But flatpak requires PPA for xenial. How can we provide support both simultaneously? Is it preferred to perform a version check before adding PPA?

**Comment by fossfreedom** [comment]
I'm sure lots of ways to tackle this.  Here is a suggestion - make of it what you will.

Change the config file to be JSON text format

Fields:
distro "xenial", package-name, ppa [optional]
"recommended" [value always in the file], package-name, ppa [optional]

json-load the file into python array.  

Get o/s codename - if in the array get the package-name  & ppa- if not available, look for the "recommended" field and get the package-name, ppa

if ppa field - add the ppa and update

install package-name.

so for flatpack we'll have a "xenial", package-name & PPA but no need for the "yakkety" separate line because this is covered by the recommended line - no PPA field.

**Comment by fossfreedom** [comment]
ok - contacted the PPA owner asking whether he intends to support yakkety/zesty users.
Since this at the moment causes a crash in budgie-welcome ... the importance of fixing this has risen so have switched this for a 16.10 update.

**Comment by fossfreedom** [comment]
ok - problem going away - PPA owner has wonderfully agreed to update the repo for yakkety users.  

Closing.
