### ISSUE TITLE
Allow users to disable budgie-welcome on startup

### ISSUE THREAD

**Issue by GrindamN** [budgie-remix/budgie-welcome#50]
Currently, the users aren't able to disable the budgie-welcome as an application that runs each time when booting into system. To disable startup users need to install gnome-tweak-tool. Disabling via builtin setting for startup items doesn't work since the budgie-welcome is not available as option to disable. 

The reason for this proposition is because after first use, the budgie-welcome becomes redundant since it isn't dynamic app. It should be however accessible from main menu as it is now.

**Comment by fossfreedom** [comment]
bottom right - click the radio button

**Comment by GrindamN** [comment]
Weird, I totally missed it. Anyhow I'm closing it. Would be nice if it was automatic.
