### ISSUE TITLE
17.04 users need to install skippy-xd via PPA

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-welcome#51]
skippy-xd will (not via us) be included in the main repositories ... however budgie-welcome can and will be installed through the main repositories.

We need (for 17.04 and later) users to add the budgie-remix PPA when someone selects to install skippy-xd found in the recommendations page.

**Comment by niyasc** [comment]
Are n't we using *budgie-remix* PPA to install *skippy-xd* currently? If so, we just have to provide repository address in `packages.json` file. So that, Welcome App will try to add repo before installing App. It won't make any difference in 16.04 and 16.10.

**Comment by fossfreedom** [comment]
currently just assuming no PPA - that was a mistake.  Good to hear this is easy to fix.

**Comment by fossfreedom** [comment]
note - similar comment about budgie-screenshot-applet - need the same fix.
